#!/usr/bin/env python3
"""
split_receptors_by_label.py

Organizes receptor PDB files into folders by label.
Example groups: SARS-CoV-2 Mpro, MERS-CoV Mpro
"""

import os
import shutil

# === USER SETTINGS ===
receptor_folder = "released-test-rec-structures"  # path where your 195 pdb files are
labels = ['MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro',
 'MERS-CoV Mpro',
 'SARS-CoV-2 Mpro',
 'SARS-CoV-2 Mpro']

# ======================

# list pdbs in consistent order
pdb_files = sorted([f for f in os.listdir(receptor_folder) if f.endswith(".pdb")])

if len(pdb_files) != len(labels):
    raise ValueError(f"Number of PDBs ({len(pdb_files)}) does not match number of labels ({len(labels)})")

# define output folder names
group_dirs = {
    "SARS-CoV-2 Mpro": "group1_SARS-CoV-2_Mpro",
    "MERS-CoV Mpro": "group2_MERS-CoV_Mpro"
}

# make directories if not exist
for d in group_dirs.values():
    os.makedirs(d, exist_ok=True)

# move or copy files
for pdb, label in zip(pdb_files, labels):
    src = os.path.join(receptor_folder, pdb)
    dst_folder = group_dirs.get(label)
    if dst_folder is None:
        print(f"Warning: unknown label '{label}' for {pdb}, skipping.")
        continue
    dst = os.path.join(dst_folder, pdb)
    shutil.copy(src, dst)   # use copy; change to shutil.move() if you prefer moving
    print(f"Copied {pdb} → {dst_folder}")

print("\ Done! Files have been organized by group.")
